### ISSUE TITLE
japanese website renewal - build

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/jp.ubuntu.com#57]
## Review
- [x] Get pages reviewed by Shibata-San - ❓pts 

## Build:
  - [x] Homepage - 5pts
  - [x] Openstack - 5pts
  - [x] Kuberentes - 5pts
  - [x] AI/ML - 5pts
  - [x] IoT - 5pts
  - [x] Enterprise Support - 5pts
  - [x] Download - 5pts
  - [x] Navigation - 2pts
  - [x] Contact us - 3pts
  - [x] Thank you - 3pts
